// <auto-generated />
using System;
using System.Collections.Generic;
using Makro.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Makro.Migrations
{
    [DbContext(typeof(MakroContext))]
    [Migration("20190207120417_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Makro.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Carbs");

                    b.Property<string>("En");

                    b.Property<decimal>("Energy");

                    b.Property<decimal>("Fiber");

                    b.Property<string>("MongoId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("PackageSize");

                    b.Property<decimal>("Protein");

                    b.Property<decimal>("ServingSize");

                    b.Property<decimal>("Sugar");

                    b.Property<int>("UserId");

                    b.Property<string>("Username");

                    b.Property<bool>("WaitingForApproval");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("Makro.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("Makro.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Activity");

                    b.Property<int>("Age");

                    b.Property<decimal>("DailyExpenditure");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<decimal>("Height");

                    b.Property<DateTime>("LastLogin");

                    b.Property<string>("MongoId");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<List<string>>("Roles");

                    b.Property<string>("Sex");

                    b.Property<decimal>("UserAddedCarbTarget");

                    b.Property<decimal>("UserAddedExpenditure");

                    b.Property<decimal>("UserAddedFatTarget");

                    b.Property<decimal>("UserAddedProteinTarget");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.Property<decimal>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Makro.Models.Food", b =>
                {
                    b.HasOne("Makro.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Makro.Models.Meal", b =>
                {
                    b.HasOne("Makro.Models.User", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
