// <auto-generated />
using System;
using System.Collections.Generic;
using Makro.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Makro.Migrations
{
    [DbContext(typeof(MakroContext))]
    partial class MakroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Makro.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnswerBody")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("QuestionId");

                    b.Property<string>("UUID")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Makro.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<List<string>>("Tags")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("UUID")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Makro.Models.ArticleImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArticleId");

                    b.Property<byte[]>("Image")
                        .IsRequired();

                    b.Property<string>("UUID")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.ToTable("ArticleImages");
                });

            modelBuilder.Entity("Makro.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AnswerId");

                    b.Property<int?>("ArticleId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("UUID")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Makro.Models.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("UUID")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("Makro.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer");

                    b.Property<DateTime>("AnsweredAt");

                    b.Property<int?>("AnsweredById");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("FeedbackBody")
                        .IsRequired();

                    b.Property<string>("UUID")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AnsweredById");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Makro.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Carbs");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("En");

                    b.Property<decimal>("Energy");

                    b.Property<decimal>("Fiber");

                    b.Property<int?>("MealId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("PackageSize");

                    b.Property<decimal>("Protein");

                    b.Property<decimal>("ServingSize");

                    b.Property<decimal>("Sugar");

                    b.Property<string>("UUID")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Foods");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Food");
                });

            modelBuilder.Entity("Makro.Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AnswerId");

                    b.Property<int?>("ArticleId");

                    b.Property<int?>("CommentId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("SharedMealId");

                    b.Property<string>("UUID")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CommentId");

                    b.HasIndex("SharedMealId");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Makro.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("DayId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("SharedDayId");

                    b.Property<string>("UUID")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("SharedDayId");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("Makro.Models.MealName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("UUID")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("MealNames");
                });

            modelBuilder.Entity("Makro.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("QuestionBody")
                        .IsRequired();

                    b.Property<string>("QuestionInformation");

                    b.Property<List<string>>("Tags")
                        .IsRequired();

                    b.Property<string>("UUID")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Makro.Models.SharedDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("UUID")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("SharedDays");
                });

            modelBuilder.Entity("Makro.Models.SharedMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("MealId");

                    b.Property<List<string>>("Tags")
                        .IsRequired();

                    b.Property<string>("UUID")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("SharedMeals");
                });

            modelBuilder.Entity("Makro.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Activity");

                    b.Property<int>("Age");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<decimal>("DailyExpenditure");

                    b.Property<string>("Email");

                    b.Property<decimal>("Height");

                    b.Property<DateTime>("LastLogin");

                    b.Property<string>("Password");

                    b.Property<List<string>>("Roles");

                    b.Property<string>("Sex");

                    b.Property<bool>("ShowTargets");

                    b.Property<string>("UUID")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<decimal>("UserAddedCarbTarget");

                    b.Property<decimal>("UserAddedExpenditure");

                    b.Property<decimal>("UserAddedFatTarget");

                    b.Property<decimal>("UserAddedProteinTarget");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.Property<decimal>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Makro.Models.EditedFood", b =>
                {
                    b.HasBaseType("Makro.Models.Food");

                    b.Property<int>("EditedById");

                    b.Property<string>("EnglishTranslation");

                    b.Property<string>("ReasonForEditing")
                        .IsRequired();

                    b.Property<bool>("WaitingForApproval");

                    b.HasIndex("EditedById");

                    b.HasDiscriminator().HasValue("EditedFood");
                });

            modelBuilder.Entity("Makro.Models.Answer", b =>
                {
                    b.HasOne("Makro.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Makro.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Makro.Models.Article", b =>
                {
                    b.HasOne("Makro.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Makro.Models.ArticleImage", b =>
                {
                    b.HasOne("Makro.Models.Article", "Article")
                        .WithMany("Images")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Makro.Models.Comment", b =>
                {
                    b.HasOne("Makro.Models.Answer", "Answer")
                        .WithMany("Comments")
                        .HasForeignKey("AnswerId");

                    b.HasOne("Makro.Models.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId");

                    b.HasOne("Makro.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Makro.Models.Day", b =>
                {
                    b.HasOne("Makro.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Makro.Models.Feedback", b =>
                {
                    b.HasOne("Makro.Models.User", "AnsweredBy")
                        .WithMany()
                        .HasForeignKey("AnsweredById");

                    b.HasOne("Makro.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Makro.Models.Food", b =>
                {
                    b.HasOne("Makro.Models.Meal")
                        .WithMany("Foods")
                        .HasForeignKey("MealId");

                    b.HasOne("Makro.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Makro.Models.Like", b =>
                {
                    b.HasOne("Makro.Models.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId");

                    b.HasOne("Makro.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId");

                    b.HasOne("Makro.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId");

                    b.HasOne("Makro.Models.SharedMeal", "SharedMeal")
                        .WithMany()
                        .HasForeignKey("SharedMealId");

                    b.HasOne("Makro.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Makro.Models.Meal", b =>
                {
                    b.HasOne("Makro.Models.Day")
                        .WithMany("Meals")
                        .HasForeignKey("DayId");

                    b.HasOne("Makro.Models.SharedDay")
                        .WithMany("Meals")
                        .HasForeignKey("SharedDayId");

                    b.HasOne("Makro.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Makro.Models.MealName", b =>
                {
                    b.HasOne("Makro.Models.User", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Makro.Models.Question", b =>
                {
                    b.HasOne("Makro.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Makro.Models.SharedDay", b =>
                {
                    b.HasOne("Makro.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Makro.Models.SharedMeal", b =>
                {
                    b.HasOne("Makro.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Makro.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Makro.Models.EditedFood", b =>
                {
                    b.HasOne("Makro.Models.User", "EditedBy")
                        .WithMany()
                        .HasForeignKey("EditedById")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
