version: '3'

services:
  backend:
    container_name: makro-restapi
    restart: always
    build: ./rest-api/
    ports:
      - '1337:80'
    depends_on:
      - db
    networks:
      - back
      - reverse-proxy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - VIRTUAL_PORT=1337
      - VIRTUAL_HOST=api.makro.diet
      - LETSENCRYPT_HOST=api.makro.diet
      - LETSENCRYPT_EMAIL=artotukki@gmail.com

  db:
    container_name: makro-db
    build: ./db/
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=makro
      - POSTGRES_USER=makro
      - POSTGRES_PASSWORD=ABC
    ports:
      - '7777:5432'
    networks:
      - back

  frontend:
    container_name: makro-angular
    restart: always
    image: makro-angular:latest
    build: ./frontend
    ports:
      - '88:88'
    networks:
      - reverse-proxy
      - back
    environment:
      - VIRTUAL_PORT=88
      - VIRTUAL_HOST=makro.diet
      - LETSENCRYPT_HOST=makro.diet
      - LETSENCRYPT_EMAIL=artotukki@gmail.com
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge
